const fakeData = {
    '0x0246fd75c62deff6711eedb0f6827f3645ccbd62': {
        productId: '0x0246fd75c62deff6711eedb0f6827f3645ccbd62',
        symbol: 'FBRX',
        users: [
            {
                address:'0x1481da69c15d4d46957fe74699cd9f1ca37200aa',
                qty: '1000',
                name: 'Danny Ocean',
                company:'Food by Rail',
                taxId: '319724045',
                holderReg1: null,
                holderReg2: null,
                holderReg3: null,
                address1: '2361 Rosemont Avenue',
                address2: null,
                address3: null,
                city: 'Orlando',
                state: 'FL',
                zip: '32801',
                country: 'USA',
                ownership: null,
                withholding: null,
                issueDate: '1/12/2018',
                cancelDate: null,
                shares: 'Series A Prefered',
                certNumber: 'c0000035345',
                costBasis: '$15.00',
                email: 'adam@gmail.com',
                phone: '321-890-2099'
            },
            {
                address:'0x1481da69c15d4d46957fe74699cd9f1ca37200ab',
                qty: '1100',
                name: 'Rusty Ryan',
                company:'Food by Rail',
                taxId: '123182966',
                holderReg1: null,
                holderReg2: null,
                holderReg3: null,
                address1: '3345 Stoneybrook Road',
                address2: null,
                address3: null,
                city: 'Orlando',
                state: 'FL',
                zip: '32803',
                country: 'USA',
                ownership: null,
                withholding: null,
                issueDate: '2/25/2018',
                cancelDate: '2/26/2018',
                shares: 'Series A Prefered',
                certNumber: 'c0000088964',
                costBasis: '$15.00',
                email: 'r_r@yahoo.com',
                phone: '407-595-2784'
            },
            {
                address:'0x1481da69c15d4d46957fe74699cd9f1ca37200ac',
                qty: '750',
                name: 'Linus Caldwell',
                company:'Food by Rail',
                taxId: '789259269',
                holderReg1: null,
                holderReg2: null,
                holderReg3: null,
                address1: '3346 Virginia Street',
                address2: null,
                address3: null,
                city: 'Chicago',
                state: 'IL',
                zip: '60609',
                country: 'USA',
                ownership: null,
                withholding: null,
                issueDate: '1/27/2018',
                cancelDate: null,
                shares: 'Series A Prefered',
                certNumber: 'c0000077703',
                costBasis: '$15.00',
                email: 'linus_@gmail.com',
                phone: '773-319-0154'
            },
            {
                address:'0x1481da69c15d4d46957fe74699cd9f1ca37200ad',
                qty: '500',
                name: 'Beatrice Ocean',
                company:'Food by Rail',
                taxId: '376690951',
                holderReg1: null,
                holderReg2: null,
                holderReg3: null,
                address1: '3686 Park Boulevard',
                address2: null,
                address3: null,
                city: 'Mason City',
                state: 'IA',
                zip: '50401',
                country: 'USA',
                ownership: null,
                withholding: null,
                issueDate: '3/13/2018',
                cancelDate: null,
                shares: 'Series A Prefered',
                certNumber: 'c0000082814',
                costBasis: '$15.00',
                email: 'b_amazing@gmail.com',
                phone: '641-512-1299'
            },
            {
                address:'0x1481da69c15d4d46957fe74699cd9f1ca37200ae',
                qty: '1200',
                name: 'Terry Benedict',
                company:'Food by Rail',
                taxId: '652903610',
                holderReg1: null,
                holderReg2: null,
                holderReg3: null,
                address1: '88 Neville Street',
                address2: 'Suite #3',
                address3: null,
                city: 'Terre Haute',
                state: 'IN',
                zip: '47802',
                country: 'USA',
                ownership: null,
                withholding: null,
                issueDate: '3/2/2018',
                cancelDate: '3/2/2018',
                shares: 'Series A Prefered',
                certNumber: 'c0000044031',
                costBasis: '$15.00',
                email: 'tben@yahoo.com',
                phone: '812-239-7247'
            },
            {
                address:'0x1481da69c15d4d46957fe74699cd9f1ca37200ag',
                qty: '1500',
                name: 'Turk Malloy',
                company:'Food by Rail',
                taxId: '742457250',
                holderReg1: null,
                holderReg2: null,
                holderReg3: null,
                address1: '1516 West Drive',
                address2: null,
                address3: null,
                city: 'Chicago',
                state: 'IL',
                zip: '60606',
                country: 'USA',
                ownership: null,
                withholding: null,
                issueDate: '2/16/2018',
                cancelDate: null,
                shares: 'Series A Prefered',
                certNumber: 'c0000079555',
                costBasis: '$15.00',
                email: 'mr_malloy@gmail.com',
                phone: '773-606-8708'
            },
            {
                address:'0x1481da69c15d4d46957fe74699cd9f1ca37200ah',
                qty: '1250',
                name: 'Saul Bloom',
                company:'Food by Rail',
                taxId: '815129261',
                holderReg1: null,
                holderReg2: null,
                holderReg3: null,
                address1: '139 Simpson Square',
                address2: null,
                address3: null,
                city: 'Clinton',
                state: 'OK',
                zip: '73601',
                country: 'USA',
                ownership: null,
                withholding: null,
                issueDate: '3/01/2018',
                cancelDate: null,
                shares: 'Series A Prefered',
                certNumber: 'c0000010439',
                costBasis: '$15.00',
                email: 'saulb@gmail.com',
                phone: '580-309-5721'
            }
        ]
    }
}

export default fakeData;